# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r

env:
   global:
     - R_BUILD_ARGS=" "
     - R_CHECK_ARGS="--as-cran"
     - NOT_CRAN="true" 

before_install:

install:

